global:
  scrape_interval: 15s

  scrape_config:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'todo-app'
      metric_path: '/metrics'
      static_configs:
        - targets: ["app:3000"]